version: '3.8'

services:
  banking-report-service:
    image: banking-report-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    environment:
      SPRING_APPLICATION_NAME: banking-report-service
      SPRING_CONFIG_IMPORT: "optional:configserver:${CONFIG_SERVICE_ENDPOINT}:${CONFIG_SERVICE_PORT}"
      SERVICE_CONFIG_SERVICE_ENDPOINT: http://config-server
      SERVICE_CONFIG_SERVICE_PORT: 8888
      SERVER_PORT: 8086
      OPENAPI_SERVICE_SERVERURL: http://config-server:8888

