spring:
  application:
    name: banking-api-gateway-service
  config:
    import: optional:configserver:http://localhost:8888

  jwt:
    secret-key: jwtHGUIUIUJghasjHGLKWPJOIDKIGjjUhkMGfkIPgf548594651gf51we5fs56f1w65f1we5f4651FGTbiIBHGUYGVHbiHEhehehe
    expiration: 3600000

#  cloud:
#    gateway:
#      routes:
#        - id: customer_service_banking
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/v1/customer/**
#            - Method=GET,POST,PUT
#        - id: account_service_banking
#          uri: http://localhost:8080
#          predicates:
#            - Path=/api/v1/account/**
#            - Method=GET,POST,PUT
#        - id: notification_service_banking
#          uri: http://localhost:8083
#          predicates:
#            - Path=/api/v1/notification/**
#            - Method=GET,POST,PUT
#        - id: reports_service_banking
#          uri: http://localhost:8086
#          predicates:
#            - Path=/api/v1/reports/**
#            - Method=GET,POST,PUT
#        - id: loans_service_banking
#          uri: http://localhost:8060
#          predicates:
#            - Path=/api/v1/loan-service/**
#            - Method=GET,POST,PUT
#        - id: transaction_service_banking
#          uri: http://localhost:8070
#          predicates:
#            - Path=/api/v1/transactions/**
#            - Method=GET,POST,PUT
#        - id: fundTransfer_service_banking
#          uri: http://localhost:8090
#          predicates:
#            - Path=/api/v1/fund_transfer/**
#            - Method=GET,POST,PUT

  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      connect-timeout: 60000

resilience4j.ratelimiter:
  instances:
    default:
      limitForPeriod: 5         # max request form 1 ip
      limitRefreshPeriod: 1s     # refresh
      timeoutDuration: 0         # time waiting
