spring:
  application:
    name: banking-api-gateway-service
  config:
    import: optional:configserver:http://localhost:8888

  jwt:
    secret-key: jwtHGUIUIUJghasjHGLKWPJOIDKIGjjUhkMGfkIPgf548594651gf51we5fs56f1w65f1we5f4651FGTbiIBHGUYGVHbiHEhehehe
    expiration: 3600000

  cloud:
    gateway:
      routes:
        - id: customer_service_banking
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/customer/**
        - id: account_service_banking
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/account/**
        - id: notification_service_banking
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/notification/**
        - id: reports_service_banking
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/reports/**
        - id: loans_service_banking
          uri: http://locallhost:8060
          predicates:
            - Path:/api/v1/loan-service/**
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      connect-timeout: 60000

resilience4j.ratelimiter:
  instances:
    ipRateLimiter:
      limitForPeriod: 5         # max request form 1 ip
      limitRefreshPeriod: 1s     # refresh
      timeoutDuration: 0         # time waiting
