server:
  port: 8060

spring:
  application:
    name: banking-loan-service

  datasource:
    url: jdbc:mysql://localhost:3306/loan_service
    username: chienma
    password: chienma_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 40MB

# OpenAPI config
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs

app:
  file:
    storage:
      directory: banking-loan-docs/

logging:
  file:
    name: logs/access_log.log
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG