server:
  port: 8060

spring:
  application:
    name: banking-loan-service
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
#    url: jdbc:mysql://localhost:3306/loan_service
#    username: chienma
#    password: chienma_password

      url: jdbc:mysql://localhost:3306/loan_service?createDatabaseIfNotExist=true
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 40MB

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# OpenAPI config
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs

app:

  file:
    storage:
      directory: banking-loan-docs/

  loan:
    disbursement:
      source-account-number: 6677738940
    repayment:
      collection-account-number: 6677738940

  fund-transfer-client:
    url: http://localhost:8090/api/v1/fund_transfer

  account-client:
    url: http://localhost:8080/api/v1/account

logging:
  file:
    name: logs/access_log.log
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
