server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: banking-config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
