-- This is sample data being inserted into the loan_type table
INSERT INTO loan_type (loan_type_name,
                       annual_interest_rate,
                       past_due_interest_rate,
                       late_payment_interest_rate,
                       prepayment_penalty_rate,
                       max_loan_amount,
                       max_loan_term_months,
                       requires_collateral,
                       review_time_days,
                       description,
                       is_active,
                       created_by,
                       created_date,
                       last_modified_by,
                       last_modified_date)
VALUES ('Vay nhu cầu nhà ở', 7.50, 10.00, 12.00, 2.00, 1000000000, 240, TRUE, 5,
        'Khoản vay dùng để mua nhà ở, hỗ trợ người vay trong việc có được ngôi nhà mơ ước.', TRUE, 'admin',
        CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP),
       ('Vay mua ô tô', 8.00, 11.00, 13.00, 2.50, 500000000, 60, TRUE, 3,
        'Khoản vay dành cho việc mua xe ô tô, hỗ trợ tài chính cho khách hàng có nhu cầu sở hữu xe.', TRUE, 'admin',
        CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP),
       ('Vay du học', 6.50, 9.00, 11.00, 1.50, 300000000, 120, FALSE, 7,
        'Khoản vay hỗ trợ chi phí học tập và sinh hoạt cho sinh viên đi du học.', TRUE, 'admin', CURRENT_TIMESTAMP,
        'admin', CURRENT_TIMESTAMP),
       ('Vay tiêu dùng không tài sản đảm bảo', 10.00, 13.00, 15.00, 3.00, 200000000, 36, FALSE, 2,
        'Khoản vay dành cho mục đích tiêu dùng cá nhân, không yêu cầu tài sản đảm bảo.', TRUE, 'admin',
        CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP),
       ('Vay sản xuất, kinh doanh', 9.00, 12.00, 14.00, 2.00, 1500000000, 180, TRUE, 10,
        'Khoản vay dành cho các doanh nghiệp sản xuất, giúp hỗ trợ vốn cho hoạt động kinh doanh.', TRUE, 'admin',
        CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
