spring:
  application:
    name: banking-account-service
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/account
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    customer-url: http://localhost:8082/api/v1/customer
    transaction-url: http://localhost:8050/api/v1/transactions